// This file has been autogenerated from a class added in the UI designer.

using System; using System.Diagnostics; using AppKit; using Foundation;  namespace HistamineSensor {
    public partial class ParameterViewController : NSViewController
    {
        public ParameterViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Do any additional setup after loading the view.
        }

        partial void StartVolt(Foundation.NSObject sender)
        {
            Debug.WriteLine(ScanRate.StringValue);
            Debug.WriteLine(Vmin.StringValue);
            Debug.WriteLine(Vmax.StringValue);

        }

        public override NSObject RepresentedObject
        {
            get
            {
                return base.RepresentedObject;
            }
            set
            {
                base.RepresentedObject = value;
                // Update the view, if already loaded.
            }
        }
    }
}
