// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace HistamineSensor
{
	public partial class SelectionViewController : NSViewController
	{
		#region Private Variables

		private NSViewController _presentor;
		#endregion

		#region Computed Properties
		
		
		public NSViewController Presentor
		{
			get { return _presentor; }
			set { _presentor = value; }
		}
		#endregion

		#region Constructors
		public SelectionViewController(IntPtr handle) : base (handle)
        {
		}
		#endregion

		#region Override Methods
		
		#endregion

		#region Private Methods
		private void CloseDialog()
		{
			Presentor.DismissViewController(this);
		}
		#endregion

		#region Custom Actions
		partial void AcceptDialog(Foundation.NSObject sender)
		{
			RaiseDialogAccepted();
			CloseDialog();
		}

		partial void CancelDialog(Foundation.NSObject sender)
		{
			RaiseDialogCanceled();
			CloseDialog();
		}
		#endregion

		#region Events
		public EventHandler DialogAccepted;

		internal void RaiseDialogAccepted()
		{
			if (this.DialogAccepted != null)
				this.DialogAccepted(this, EventArgs.Empty);
		}

		public EventHandler DialogCanceled;

		internal void RaiseDialogCanceled()
		{
			if (this.DialogCanceled != null)
				this.DialogCanceled(this, EventArgs.Empty);
		}
		#endregion
	}
}